swagger: "2.0"
info:
  description: "This is a Flashcard server.  You can find out more about Swagger at <a href=\"http://swagger.io\">http://swagger.io</a> or on irc.freenode.net, #swagger.  You can use the api key \"special-key\" to test the authorization filters"
  version: 1.0.0
  title: Swagger Flashcard YAML
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: /v1
tags:
  - name: decks
    description: All about decks data
#  - name: user
#    description: Access to Petstore orders
#    externalDocs:
#      description: Find out more about our store
#      url: "http://swagger.io"
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: api_key    
security:
  - api_key: []
paths:
  /decks:
    get:
      tags:
        - deck
      summary: Find all decks available
      x-swagger-router-controller: DeckController
      description: Return all set of decks
      operationId: getDecks
      parameters:
        - $ref: "#/parameters/user_id"
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Decks"
        500:
          $ref: "#/responses/Standard500ErrorResponse"  
    post:
      tags:
        - deck
      summary: Create a new deck
      parameters:
        - name: deck
          in: body
          description: The deck object that will be inserted
          schema:
            $ref: "#/definitions/Deck"
      responses:
        201:
          $ref: "#/responses/Standard201CreatedResponse" 
        500:
          $ref: "#/responses/Standard500ErrorResponse"  
  "/decks/{id}":
    parameters:
      - $ref: "#/parameters/id"
    get:
      tags:
        - deck
      summary: Find deck by ID
      x-swagger-router-controller: DeckController
      description: Returns a single set of deck
      operationId: getDeckById
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Deck"
        404:
          description: Deck not found
        500:
          $ref: "#/responses/Standard500ErrorResponse"  
    put:
      tags:
        - deck
      summary: Updates a deck in the store with form data
      description: "Update a deck by ID"
      operationId: updateDeck
      parameters:
        - name: deck
          in: body
          description: Deck object that will be changed
          required: true
          schema:
            $ref: "#/definitions/Deck"
      responses:
        204:
          description: Deck sucessfully updated.
        500:
          $ref: "#/responses/Standard500ErrorResponse"  
    delete:
      tags:
        - deck
      summary: Delete a deck
      description: "deleting deck by id and using teacher account"
      operationId: deleteDeck
      responses:
        204:
          description: Deck successfully deleted.
        404:
          $ref: "#/responses/ObjectDoesNotExistResponse"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
  /users:
    get:
      tags:
        - user
        - mocked
      x-swagger-router-controller: UserController
      description: Return all set of decks
      operationId: getUsers
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Users"
          examples:
            application/json:
              - id: 1
                auth_level: admin
                username: Astrid
              - id: 2
                auth_level: teacher
                username: Teachername
              - id: 3
                auth_level: student
                username: Studentname
        #500:
        #  $ref: "#/responses/Standard500ErrorResponse"
    post:
      tags:
        - user
        - mocked
      description: Add a user
      operationId: addUser
      parameters:
        - name: Input
          required: true
          in: body
          description: The information about the user to be added
          schema:
              $ref: "#/definitions/AddUserInput"
      responses:
        201:
          $ref: "#/responses/Standard201CreatedResponse"
        #500:
        #  $ref: "#/responses/Standard500ErrorResponse"
  "/users/{id}":
    parameters:
      - $ref: "#/parameters/id"
    get:
      tags:
        - user
        - mocked
      summary: Find a user by ID
      x-swagger-router-controller: UserController
      description: Return a user object identified by its id
      operationId: getUserById
      responses:
        200:
          description: successful operation
          schema:
              $ref: "#/definitions/User"
          examples:
              application/json:
                - id: 1
                  auth_level: admin
                  username: Astrid
        #500:
        #  $ref: "#/responses/Standard500ErrorResponse"
    put:
      summary: Update a user by ID
      x-swagger-router-controller: UserController
      description: Update a user by ID
      operationId: updateUserById
      parameters:
        - name: user
          required: true
          in: body
          description: The information about the user to be added
          schema:
              $ref: "#/definitions/AddUserInput"
      responses:
        200:
          description: successful operation
          examples:
            application/json:
              - username: Astrid
                password: 12345
                auth_level: admin
    delete:
      summary: Delete a user by ID
      x-swagger-router-controller: UserController
      description: Delete a user by it's ID
      operationId: deleteUserById
      responses:
        200:
          description: successful operation
        #500:
        #  $ref: "#/responses/Standard500ErrorResponse"
  /authlevel:
      get:
        tags:
          - user
        x-swagger-router-controller: UserController
        description: Return all available user level of authorization
        operationId: getUsersAuth
        responses:
          200:
            description: successful operation
            schema:
              $ref: "#/definitions/AuthLevel"
            examples:
              application/json:
                - id: 0
                  auth: admin
                - id: 1
                  auth: teacher
                - id: 2
                  auth: student
  /login:
    post:
      tags:
        - user
        - mocked
      summary: login
      x-swagger-router-controller: UserController
      operationId: login
      parameters:
        - name: loginInfo
          in: body
          description: Login attempt
          schema:
            $ref: "#/definitions/Login"
      responses:
        200:
          description: successful operation
          schema:
              $ref: "#/definitions/User"
          examples:
            application/json:
              - id: 1
                auth_level: admin
                username: Astrid
        403:
          description: unsuccessful login
  /generate-cards:
    post:
      tags:
        - generate
      summary: To generate card by request
      x-swagger-router-controller: DeckController
      description: Return all set of decks
      operationId: generateCards
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Deck"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
      parameters:
        - name: generatesCard
          in: body
          description: The request from frontend
          schema:
            $ref: "#/definitions/GenerateCards"

definitions:
  AuthLevel:
    properties:
      id:
        type: integer
      auth:
        type: string
  User:
    properties:
      id:
        type: integer
      username:
        type: string
      auth_level:
        type: string
    xml:
      name: User
  Users:
    type: array
    items:
      $ref: "#/definitions/User"
  AddUserInput:
    properties:
      username:
        type: string
      password:
        type: string
      auth_level:
        type: integer
    xml:
      name: Input data for adding user
  Login:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  Card:
    properties:
      id:
        type: integer
      problem:
        type: string
      answer:
        type: string
    xml:
      name: Card
  Deck:
    required:
      - user_id
    properties:
      id:
        type: integer
      numProblems:
        type: integer
      name:
        type: string
      description:
        type: string
      user_id:
        type: integer
      user_name:
        type: string
      created:
        type: string
      changed:
        type: string
      private:
        type: boolean
      flashcards:
        $ref: "#/definitions/Card"
    xml:
      name: Deck
  Decks:
    type: array
    items:
      $ref: "#/definitions/Deck"
  Operators:
    properties:
      minus:
        type: boolean
      add:
        type: boolean
      div:
        type: boolean
      multi:
        type: boolean
  GenerateCards:
    properties:
      min:
        type: integer
      max:
        type: integer
      numberSolution:
        type: integer
      operators:
        $ref: "#/definitions/Operators"
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
  ObjectDoesNotExistResponse:
    description: The object was not found in
  Standard201CreatedResponse:
    description: Created entity
parameters:
  id:
    name: id        
    in: path
    required: true
    description: The identifier of the object
    type: integer
    x-example: 1
  user_id:
    name: user_id
    in: query
    description: The id for the user
    type: integer
    x-example: 1